rest-for-physics/tracklib

- src/TRestTrackAnalysisProcess.cxx
This commit introduces gaussian fits to the size of the first and second maximum energy tracks, using the relevant method from TRestHits. Some revision and renaming has also been done.
> TRestTrackAnalysisProcess: new gaussian observables added

- src/TRestTrackAnalysisProcess.cxx
New observables regarding the shape of the events have been implemented for the first and second tracks. In particular:
- MaxTrackSigmaZ and MaxTrackGaussSigmaZ (these takes XYZ tracks, so it's always 0)
- MaxTrack_XZ_GaussSigmaZ
- MaxTrack_YZ_GaussSigmaZ
- MaxTrack_XYZ_GaussSigmaZ (for which a hits variable is created so that it includes both XZ and YZ tracks)
- MaxTrack_XYZ_skewXY and MaxTrack_XYZ_skewZ (for which a hits variable is created so that it includes both XZ and YZ tracks).
Similar observables have been created for the second track.
> TRestTrackAnalysisProcess: new sigma, skewness observables

- src/TRestTrackAnalysisProcess.cxx
Solved the issues with null pointers when calling GetHits in ```TRestTrackAnalysisProcess```
> TRestTrackAnalysisProcess fix null pointer access

- inc/TRestTrackEvent.h
- src/TRestTrackEvent.cxx
After new changes in the code, it seems that `DrawEvent` is not working for some inherited classes from `TRestEvent`
This PR fix this bug by replacing:
```
- TPad* DrawEvent(TString option = "");
+ TPad* DrawEvent(const TString& option = "");
```
> Fixing bug on inheritance of DrawEvent from base class

- inc/TRestTrackAnalysisProcess.h
- inc/TRestTrackBlobAnalysisProcess.h
- inc/TRestTrackLinearizationProcess.h
- inc/TRestTrackPathMinimizationProcess.h
- inc/TRestTrackReconnectionProcess.h
- inc/TRestTrackReductionProcess.h
- inc/TRestTrackViewerProcess.h
- src/TRestTrackAnalysisProcess.cxx
- src/TRestTrackDetachIsolatedNodesProcess.cxx
- src/TRestTrackLineAnalysisProcess.cxx
- src/TRestTrackLinearizationProcess.cxx
- src/TRestTrackPathMinimizationProcess.cxx
- src/TRestTrackReconnectionProcess.cxx
- src/TRestTrackReductionProcess.cxx
Related with https://github.com/rest-for-physics/framework/pull/225:
- Renamed custom `endl` to `RESTendl`
- Renamed other logger functions
- `info` --> `RESTInfo`  
- `debug` --> `RESTDebug`
- `essential` --> `RESTEssential`
- `warning` --> `RESTWarning`
- `fout` --> `RESTcout`
- `ferr` --> `RESTError`
> Renaming endl to RESTendl and other logger functions

- inc/TRestTrackPathMinimizationProcess.h
- src/TRestTrackPathMinimizationProcess.cxx
- src/TRestTrackReconnectionProcess.cxx
- tsp/inc/config.h
Related to https://github.com/rest-for-physics/framework/pull/231. Array initialization with dynamic length is not available for msvc. Changed to vector. e.g. `Double_t x[nHits];` --> `vector<Double_t> x(nHits);`
> replaced dynamic length array initializaion

- src/TRestTrackLinearizationProcess.cxx
After https://github.com/rest-for-physics/framework/pull/263 members of `TRestHits` such as `fEnergy` or `fX` are made protected so this PR updates all access to this members using getter.
Related PR:
* https://github.com/rest-for-physics/framework/pull/263
> Fix compilation problem after making TRestHits members protected

- src/TRestTrackAnalysisProcess.cxx
The observable MaxTrack_YZ_SigmaZ was wrongly returning the value for sigma Y instead of sigma Z.
> MaxTrack_YZ_SigmaZ now actually stores Z instead of Y

- CMakeLists.txt
- src/TRestTrackAnalysisProcess.cxx
The sigma and gauss sigma balance in Z is computed for the first track.
> New observables for Z sigma balance

- src/TRestTrackAnalysisProcess.cxx
- src/TRestTrackLineAnalysisProcess.cxx
New observables were added to `TRestTrackAnalysisProcess`:
- `MaxTrack_YZ_nHits` and `MaxTrack_XZ_nHits` for the number of hits on the maximum track
- `MaxTrack_XYZ_SigmaZ2` for the sigmaZ on the XZ + YZ projections.
Bug fix on the calculation of trackBalance on `TRestTrackLineAnalysisProcess` and adding new obserbable  `trackBalance` for the total track balance XZ + YZ projections
> Adding new observables to TRestTrackAnalysisProcess and bug fix on TRestTrackLineAnalysisProcess

- inc/TRestTrackEvent.h
- inc/TRestTrackLineAnalysisProcess.h
- src/TRestTrackEvent.cxx
- src/TRestTrackLineAnalysisProcess.cxx
New methods were added in `TRestTrackLineAnalysisProcess` and implemented under `TRestTrackEvent`:
-  New observable added `relativeZ` that computes the relative Z position of the track to determine if it is `upwards` or `downwards`
- New method to reconstruct the track in 3D and retreive the origin and the end of the track
> New methods added for track analysis

- src/TRestTrackPathMinimizationProcess.cxx
Adressing compilator warning on gcc 12.2
> Adressing compilator warning on gcc 12.2

- inc/TRestTrackAnalysisProcess.h
- inc/TRestTrackBlobAnalysisProcess.h
- inc/TRestTrackDetachIsolatedNodesProcess.h
- inc/TRestTrackLineAnalysisProcess.h
- inc/TRestTrackLinearizationProcess.h
- inc/TRestTrackPathMinimizationProcess.h
- inc/TRestTrackPointLikeAnalysisProcess.h
- inc/TRestTrackReconnectionProcess.h
- inc/TRestTrackReductionProcess.h
- inc/TRestTrackViewerProcess.h
Removal of custom `typedef REST_Reflection::TRestReflector any` since it is misleading with `std::any`.
The custom typedef `any` has been replaced by existing `typedef REST_Reflection::TRestReflector RESTValue`
Related PR https://github.com/rest-for-physics/framework/pull/471
> Removal of custom typedef any since it is misleading with std::any

- src/TRestTrackAnalysisProcess.cxx
- src/TRestTrackEvent.cxx
Some observables doesn't work properly for simulation tracks (XYZ tracks), only for real ones (XZ or YZ tracks).
Here I try to solve this issue for SecondMaxTrackEnergy.
> Track observables for simulation events (XYZ tracks)

- inc/TRestTrack3DAnalysisProcess.h
- src/TRestTrack2DAnalysisProcess.cxx
- src/TRestTrack3DAnalysisProcess.cxx
Implementation of an analysis process for pure XYZ tracks (simulation typically). 
Issue #41
> TRestTrack3DAnalysisProcess 

- src/TRestTrack2DAnalysisProcess.cxx
Corrected way to find some observables.
These observables are found using the function (example for the first of the changes) _**XZ_YZ_SigmaXYBalance**_, that previously used as input _**energiesY[0].first**_. This can, however, differ as the map _**energiesY**_ is sorted and these values will change (_**energiesY[0].first**_ can be 4, for example). The way the function is defined _**XZ_YZ_SigmaXYBalance[i] = (XZ_SigmaX[energiesX[i].first] - YZ_SigmaY[energiesY[i].first]) / (XZ_SigmaX[energiesX[i].first] + YZ_SigmaY[energiesY[i].first]);**_ i will be 4 in this example and will call _**XZ_SigmaX[energiesX[4].first]**_ instead of the desired _**XZ_SigmaX[energiesX[0].first]**_ that will correspond to the highest energy track, while _**XZ_SigmaX[energiesX[4].first]**_ is the 4th highest …
> Correct observable definitions

- src/TRestTrack2DAnalysisProcess.cxx
- src/TRestTrack3DAnalysisProcess.cxx
There are two different problems:
- Some subruns are not analyzed when using the Tracks2D or Tracks3D analysis. I don´t know why!! It happens in some subruns but not in others. For example, it doesn´t work for "/storage/iaxo/iaxo-lab/data/R02145_Calibration_Vm_325_Vd_900_Pr_1.25_Gain_0x0_Shape_0xF_Clock_0xA-002.aqs" but it does for "/storage/iaxo/iaxo-lab/data/R02145_Calibration_Vm_325_Vd_900_Pr_1.25_Gain_0x0_Shape_0xF_Clock_0xA-001.aqs".
But for the other one:
- For some events a TRestReflectorError is shown:
It comes in 3, this will be important later.
> Work on Tracks2D and 3D - Comment checkpoint

- inc/TRestTrack.h
- inc/TRestTrack2DAnalysisProcess.h
- inc/TRestTrack3DAnalysisProcess.h
- inc/TRestTrackAnalysisProcess.h
- inc/TRestTrackBlobAnalysisProcess.h
- inc/TRestTrackDetachIsolatedNodesProcess.h
- inc/TRestTrackEvent.h
- inc/TRestTrackLineAnalysisProcess.h
- inc/TRestTrackLinearizationProcess.h
- inc/TRestTrackPathMinimizationProcess.h
- inc/TRestTrackPointLikeAnalysisProcess.h
- inc/TRestTrackReconnectionProcess.h
- inc/TRestTrackReductionProcess.h
- inc/TRestTrackViewerProcess.h
- src/TRestTrack.cxx
- src/TRestTrack2DAnalysisProcess.cxx
- src/TRestTrack3DAnalysisProcess.cxx
- src/TRestTrackAnalysisProcess.cxx
- src/TRestTrackBlobAnalysisProcess.cxx
- src/TRestTrackDetachIsolatedNodesProcess.cxx
- src/TRestTrackEvent.cxx
- src/TRestTrackLineAnalysisProcess.cxx
- src/TRestTrackLinearizationProcess.cxx
- src/TRestTrackReconnectionProcess.cxx
- src/TRestTrackViewerProcess.cxx
I did some review. These are the most notable changes:
- `TRestTrack` no longer inherits from `TObject`. There is no need for this as far as I am aware.
- Imports are formatted according to the style of the other REST-for-Physics libraries.
- Use `std::vector::emplace_back` instead of `std::vector::push_back` in many instances.
- Fix a few potential bugs where the `&&` operator was incorrectly written as `&`.
- Fix a lot of typos (shame on you @DavidDiezIb).
> Code Review

- src/TRestTrack2DAnalysisProcess.cxx
Change type of needed observables to avoid TRestReflector warning
> Solve type issue

- src/TRestTrack2DAnalysisProcess.cxx
> Check energiesX

- src/TRestTrack2DAnalysisProcess.cxx
- src/TRestTrack3DAnalysisProcess.cxx
Previously, the XZ_SigmaZ and YZ_SigmaZ observables were being find by simply using GetSigmaZ2(). This GetSigmaZ2() is the squared value of SigmaZ, for example we can see that the GetSigmaX() does the same calculations as GetSigmaZ2() but the applies the squared root. By adding sqrt we find XZ_SigmaZ instead of XZ_SigmaZ2, which is what we were calculating before.
For a given file we see how we get the squared root of 2 of the observables of interest, so instead of sigmaZ2 we get SigmaZ as the observable name indicates:
_Fig 1: Before the change we had this values._
_Fig 2: After the change._
> Add sqrt to SigmaZ values since it is calculated with GetSigmaZ2()
